version: '3'

services:
  powerstudio-gateway:
    image: gaia-powerstudio-gateway:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - stack.env
    networks:
      - gaia
    pull_policy: build

networks:
  gaia:
    external:
      name: gaia