version: '3'

services:
  gaia-powerstudio-gateway:
    image: gaia-powerstudio-gateway:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - stack.env
    networks:
      - emqx-network
    pull_policy: build

networks:
  emqx-network:
    external: true